//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMangementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patien
    {
        public Patien()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string BloodType { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
