//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMangementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public int DepartmentID { get; set; }
        public int UserID { get; set; }
        public System.DateTime MeetTime { get; set; }
        public decimal ReservationPrice { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patien Patien { get; set; }
        public virtual User User { get; set; }
    }
}
